### PR TITLE
Updated "manage-attendees-frontend"

### PR DESCRIPTION
**Pull request by DannyThorne01**
## Summary

Implements the ManageAttendees organism in the `manage-attendees-frontend` branch
Closes TBD

## Testing

Checkout to `manage-attendees` branch
It is recommended to use a `/frontend/src/pages/text.tsx` as a page to view the component. For example:
```
import ManageAttendees from "@/components/organisms/ManageAttendees";

const Test = () => {
  return <ManageAttendees />;
};

export default Test;
```

## Notes
image
image
image

Notes on PR review
The checkbox should not be checked by default : Bug, the checkboxes cannot be defaulted to be unchecked at the moment.
Can you adjust the width of the of checkbox column: Done!
Remember to include the icons in the buttons just like the designs: Bug, this will be fixed by allowing the `Button` atom to take in a React Component instead of just a string.

### CODE REVIEW

**Review by louisvalencia — APPROVED** [review]
LGTM 🐥

**Review by sophwa — CHANGES_REQUESTED** [review]
Hello! This looks good so far and works well! One thing I noticed:
- Comparing it to the design on Figma, is there a way to close the whitespace between the checkbox and Name column on the laptop view?

**Review by snehar27 — COMMENTED** [review]
Looks really good!

Just one quick thing--In the Figma, for mobile view, the information of the volunteer gets collapsed into a button and only the name of the volunteer is shown. This might be a quick change that you can make! Other than that, looks great to me!

**Review by akinfelami — APPROVED** [review]

**Review by snehar27 — APPROVED** [review]
Looks great!

**Review by sophwa — APPROVED** [review]

**Review by jasozh — APPROVED** [review]

**Pull request merged**
