### PR TITLE
User profile frontend

### LINKED ISSUE #108: Implement User Profile (frontend)
**Branch:** `user-profile-frontend`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0).
2. Implement the `UserProfile` component so that it looks like the following:
Image
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).
### Acceptance Criteria
- [ ] Users can see a user profile.

### Notes
- **The only parameter passed in is the `userid`**. Fill out the actual content with placeholder text for now.

### PR DESCRIPTION
**Pull request by Y1chenYao**
## Summary
- Implements `UserProfile`
- Closes #108 

## Screenshot
image

## Testing

Checkout `user-profile-frontend`.
It is recommended to use a `text.tsx` as a page to view the component. For example,
```
import React from "react";
import UserProfile from "@/components/organisms/UserProfile";


const Test = () => {
  return (
    <UserProfile userid="1"/>
  );
};

export default Test;
```

## Notes
- `IconText` is adapted from the previous PR, which hasn't been merged to main yet. The styling of `IconText` might still need adjustment to align icon with the text (children).

### CODE REVIEW

**Review by akinfelami — CHANGES_REQUESTED** [review]
Hi! great work on this so far. Some things to review:
- The styling is a bit off - the icons and the corresponding texts are not centered in the div that wraps them. You would notice that the calendar text seems to be hanging lower than the date. I think you would need to modify `IconText` for this. Simply add a `flex items-center justify-center`. 
#### But this might break stuff. Ultimately, you are trying to achieve something similar to what is it `Avatar` component  in molecule so that might help

**Comment by Y1chenYao** [comment]
Hi Akin! I fixed `IconText` by adding vertically alignment.

image

**Review by DannyThorne01 — APPROVED** [review]
Looks Good!

**Review by louisvalencia — APPROVED** [review]
Icons and texts are now aligned on my end

**Review by akinfelami — APPROVED** [review]

**Review by jasozh — APPROVED** [review]
Moved placeholder text from hardcoded text inside `UserProfile` to prop params.

**Pull request merged**
