### PR TITLE
Prevent past events from being edited

### PR DESCRIPTION
**Pull request by jasozh**
## Summary

When a supervisor tries to edit an event that happened in the past, the Save changes button and Cancel event button are disabled, and an alert is shown instead.

## Testing

image

### CODE REVIEW

**Comment by akinfelami** [comment]
Using string type instead of date type will break things in different places because the helpers function to converttoIso is being used by different components.

**Review by akinfelami — COMMENTED** [review]
lgtm. I changed the types back to Date because it was breaking deployment. I tested it and it still worked. Can you share why you reverted to string?

**Comment by jasozh** [comment]
The reason I changed it to `string` is because the current date type is actually lying; it's not actually a `Date` object but a string. If the parameters to `convertToISo` were actually `Date` objects, there would be no need to do `new Date(inputDate)` because `inputDate` would already be a `Date`. TypeScript doesn't actually enforce types on runtime so it just passes.

**Comment by akinfelami** [comment]
A

> The reason I changed it to `string` is because the current date type is actually lying; it's not actually a `Date` object but a string. If the parameters to `convertToISo` were actually `Date` objects, there would be no need to do `new Date(inputDate)` because `inputDate` would already be a `Date`. TypeScript doesn't actually enforce types on runtime so it just passes.

I see. I did notice it was breaking stuff in other components that actually passed in `Date` objects to the `convertToIso` function. I am fine with either but it will take some effort to refactor others

**Review by akinfelami — APPROVED** [review]

**Comment by akinfelami** [comment]
btw I added backend protection in this pr

**Pull request merged**
