### PR TITLE
Event registration frontend

### LINKED ISSUE #81: Implement Event Registration
**Branch:** `event-registration-frontend`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0) for the View Events pages.
2. Implement the `EventRegisterForm` component so that it looks like the following:
Image
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).
### Acceptance Criteria
- [ ] Users can see the Event Register Form. This must be mobile friendly (see Figma)
- [ ] Clicking on the button opens the modal

### Notes
- Use the following components: `IconText`, `EventDetails`, `Checkbox`, `Button`, `Modal`

### PR DESCRIPTION
**Pull request by bananahz**
## Summary
- Implements `EventRegistrationForm`.
- Implements clickable button that pops up modal. 
- Closes #81. 

### Screenshots
Web View
image

Mobile View

## Testing

It is recommended to use a `text.tsx` as a page to view the component. For example,
```
import React from "react";
import EventRegisterForm from "@/components/organisms/EventRegisterForm";

const Test = () => {
  return (
    <EventRegisterForm eventid="1"/>
  );
};

export default Test;
```
To visualize EventDetails as a grey box, insert this line in EventDetails.tsx
```
return <div className="h-40 bg-gray-300">event details</div>;
```

### CODE REVIEW

**Review by akinfelami — CHANGES_REQUESTED** [review]
Hi! Good work on this so far! Two quick things:
Can you share how you tested this? I can see screenshots of the web site but I would want to see it myself
It looks like the web view implementation is different from the figma? Maybe I missed it but why is the event details just a grey box?

**Comment by Y1chenYao** [comment]
> Hi! Good work on this so far! quickly: Can you share how you tested this? I can see screenshots of the web site but I would want to see it myself

Hi Akin! I've edited the `Testing` part of the pr. :)

**Review by akinfelami — CHANGES_REQUESTED** [review]
Good job on this one guys!

It appears the checkbox is checked by default. I'm not sure if that should be. Let's chat about this. 

Also, could you include some validation to make sure a user can only click the register if the checkbox is checked?

**Comment by snehar27** [comment]
Looks great!

**Review by snehar27 — COMMENTED** [review]
This looks great!

**Review by sophwa — APPROVED** [review]
Looks good! Design follows the same layout of the ticket!

**Review by snehar27 — APPROVED** [review]

**Review by akinfelami — APPROVED** [review]
lgtm

**Review by jasozh — APPROVED** [review]
Looks good! I just changed the **Return to My Events** button to use the `IconText` class so that everything is standardized.

**Pull request merged**
