### PR TITLE
Search bar frontend

### LINKED ISSUE #106: Implement Search Bar (frontend)
**Branch:** `search-bar-frontend`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0).
2. Implement the `SearchBar` component so that it looks like the following:
Image
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).
### Acceptance Criteria
- [ ] Users can see a search bar, where the content of the search bar is passed in as a parameter.

### Notes
- Use MUI components

### PR DESCRIPTION
**Pull request by snehar27**
## Summary

Closes #106 
Implements `SearchBar`

image

## Testing

It is recommended to use a Test.tsx as a page to view the component. For example, this code can be used:

```
import React from "react";
import SearchBar from "@/components/atoms/SearchBar";

const Test = () => {
  return <SearchBar value={""} />;
};

export default Test;
```

### CODE REVIEW

**Review by Y1chenYao — CHANGES_REQUESTED** [review]
I tested the `SearchBar` and it looks pretty good. :)

There are a few things I would address:
- `Test.tsx` should be removed from pr.
- This pr contains changes made to `EventCard`, `IconText` etc. which are not relevant to searchbar.

**Review by Y1chenYao — APPROVED** [review]
Looks pretty good!

**Review by bananahz — APPROVED** [review]
lgtm!

**Review by akinfelami — APPROVED** [review]

**Review by jasozh — APPROVED** [review]
Changed underlying component to `TextField` and added `onChange` and `onClick` props

**Pull request merged**
