### PR TITLE
Manage user profile frontend

### LINKED ISSUE #109: Implement Manage User Profile (frontend)
**Branch:** `manage-user-profile-frontend`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0) for the **Admin Manage Users Flow** pages.
2. Implement the `ManageUserProfile` component so that it looks like the following:
Image
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).
### Acceptance Criteria
- [x] Users can see the `ManageUserProfile` component and click between the **Status**, **Registration**, and **Verify Certificate Request** tabs to see placeholder information..

### Notes
- **Use the View Events component as inspiration**. See how we use `TabContainer` and use that component.
- Don't worry about the pagination styles on the table. Just use the `Table` component we already have.
- Don't worry about the icons on the tabs. **Have the icons ready in a piece of sample code, but do not worry about passing it into `TabContainer`.**

### PR DESCRIPTION
**Pull request by bananahz**
## Summary
- Implements `ManageUserProfile` component. 
- Closes #109 

#### Web View 
image

#### Mobile View
image

#### Web View 
image

#### Mobile View
image

#### Web View 
image

#### Mobile View
image

## Testing

Checkout `manage-user-profile-frontend`
Use `test.tsx` to view this page 

```
import React from "react";
import ManageUserProfile from "../components/organisms/ManageUserProfile";

const Test = () => {
  return <ManageUserProfile userid="1" />;
};

export default Test;
```

## Notes
- We are unable to change the thickness of the progress bar currently

### CODE REVIEW

**Review by akinfelami — CHANGES_REQUESTED** [review]
Hey! Great work so far. 

There is a major bug in your code. You remove the `UserProfile.tsx` file. Why? You import it in  `ManageUserProfile.tsx` so it is throwing errors and I can't start the project

**Comment by bananahz** [comment]
Oops! Added `UserProfile` back!

**Review by DannyThorne01 — COMMENTED** [review]
Looks Good!

**Review by DannyThorne01 — APPROVED** [review]

**Review by louisvalencia — APPROVED** [review]
LGTM 🐥

**Review by akinfelami — APPROVED** [review]

**Review by jasozh — APPROVED** [review]
Replaced header nav with IconText, fixed padding and refactored code

**Pull request merged**
