### PR TITLE
Completed Manage Users Frontend

### LINKED ISSUE #107: Implement Manage Users (frontend)
**Branch:** `manage-users-frontend`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0) for the **Admin Manage Users Flow** pages.
2. Implement the `ManageUsers` component so that it looks like the following:
Image
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).
### Acceptance Criteria
- [ ] Users can see the `ManageUsers` component and click between the **Active** and **Blacklisted** tabs to see tables of placeholder users.

### Notes
- Ignore the pagination styling in the Figma; just use the `Table` component we already have defined
- **Do not implement the searchbar**. Import the component in your code but you do not need to implement it.
- **Use the View Events component as inspiration**. See how we use `TabContainer` and use that component.
- Don't worry about the icons on the tabs. **Have the icons ready in a piece of sample code, but do not worry about passing it into `TabContainer`.**

### PR DESCRIPTION
**Pull request by louisvalencia**
## Summary

- Implements `ManageUsers` component. 
- Closes #107 

#### Figma Design
Screenshot 2023-10-02 at 21 21 24

#### Web View 
Screenshot 2023-10-02 at 21 23 31

#### Mobile View
Screenshot 2023-10-02 at 21 12 07

## Testing

- Checkout `manage-users-frontend`
- Create the file `test.tsx` in frontend -> src -> pages with the code

```
import ManageUsers from "@/components/organisms/ManageUsers";
import React from "react";

/** A Login page */
const Test = () => {
  return <ManageUsers></ManageUsers>;
};

export default Test;
```

## Notes
- Was not able to bold the headers of the columns as seen in the Figma designs. Would need to change the `Table` molecule.
- Was instructed not to add the View Profile icon and the Search Bar component.
- Unsure if the text fonts/weight/size align with that of Figma.

### CODE REVIEW

**Review by akinfelami — CHANGES_REQUESTED** [review]
Hi! Great work on this so far. Some things to review:
- The mobile can still look better. Take a look at `ViewEvents` . Do they do something different to include some horizontal scrolling in mobile view? 
- In response to your notes:
  - Can you attempt to modify the `Table` molecule so it can support bold headings? I think it's better to address it as soon as possible to prevent future tech debt.
  - About the icons, I believe you can include it in the eventColumns Grid you created. This will allow us to get a feel of the page as it is in figma
  - Don't worry too much about the text fonts/weight/size aligning with Figma. Much of these will still be altered when we start applying HiFI styling. For now, your discretion will suffice.

**Comment by louisvalencia** [comment]
> Hi! Great work on this so far. Some things to review:
> 
> * The mobile can still look better. Take a look at `ViewEvents` . Do they do something different to include some horizontal scrolling in mobile view?
> * In response to your notes:
>   
>   * Can you attempt to modify the `Table` molecule so it can support bold headings? I think it's better to address it as soon as possible to prevent future tech debt.
>   * About the icons, I believe you can include it in the eventColumns Grid you created. This will allow us to get a feel of the page as it is in figma
>   * Don't worry too much about the text fonts/weight/size aligning with Figma. Much of these will still be altered when we start applying HiFI styling. For now, your discretion will suffice.

As checked with Jason, did not modify Table molecule to support bold headings nor added icons. Was able to include horizontal scrolling in mobile view and bolded headers.

**Review by sophwa — APPROVED** [review]
If addressed Akin's comments and instructed not to add the View icon on the button, then looks good to me! Incorporates the Figma design well and everything seems to function properly.

**Review by snehar27 — COMMENTED** [review]
Looks good! Quick thing about the mobile view--on the Figma, for the mobile view, there seems to be horizontal scrolling instead of small columns to fit the screen, so that might be a change that should be made. Other than that, looks great to me :)

**Comment by louisvalencia** [comment]
> Looks good! Quick thing about the mobile view--on the Figma, for the mobile view, there seems to be horizontal scrolling instead of small columns to fit the screen, so that might be a change that should be made. Other than that, looks great to me :)

already did this :)

**Comment by louisvalencia** [comment]
> t the mobile view--on the Figma, for the mobile view, there seems to be horizontal scrolling instead of small columns to fit the screen, so that might be a change that should be made. Other than that, looks great to me :)

I did this :)

**Review by snehar27 — APPROVED** [review]
Looks good to me!

**Review by sophwa — APPROVED** [review]
LGTM !

**Review by akinfelami — APPROVED** [review]

**Review by jasozh — APPROVED** [review]
Added search bar and increased padding

**Pull request merged**
